# Site
title: Harman Singh Hira
subtitle: "Just another coder I guess..."
description: "Welcome to my personal blog where I share my thoughts on coding, technology, and life."
keywords: Harman Singh Hira, hsinghhira, hsinghhira.me, blog, personal blog, hexo, hexo theme minima
author: Harman Singh Hira
language: en
timezone: Pacific/Auckland
url: http://me.hsinghhira.me/
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

meta_generator: true

date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: "mtime"

per_page: 10
pagination_dir: page

include:
exclude:
ignore:

all_minifier: true
html_minifier: true
css_minifier: true
js_minifier: true

theme: minima

deploy:
  type: git
  repo: https://github.com/HSinghHira/Its-Me.git
  branch: page
  message: "Last Update: {{ now('MM-DD HH:mm:ss') }}"
  cname: me.hsinghhira.me

lazyload:
  enable: true
  onlypost: false
  loadingImg: # /images/loading.gif
  isSPA: false
  preloadRatio: 3

feed:
  limit: 20
  order_by: "-date"
  tag_dir: "tag"
  category_dir: "category"
  rss:
    enable: true
    output: "rss.xml"
  atom:
    enable: true
    output: "atom.xml"
  jsonFeed:
    enable: true
    output: "feed.json"

seo:
  html:
    enable: true
    fix: true
    exclude:
      - "*.min.{htm,html}"
  css:
    enable: true
    exclude:
      - "**/*.min.css"
  js:
    enable: true
    concat: false
    exclude:
      - "**/*.min.js"
    options:
      compress:
        dead_code: true
      mangle:
        toplevel: true
        safari10: true
  schema:
    article:
      enable: true
    breadcrumb:
      enable: true
    sitelink:
      enable: true
    homepage:
      enable: true
  img:
    enable: true
    broken: false
    default: https://upload.wikimedia.org/wikipedia/commons/6/65/No-Image-Placeholder.svg
    onerror: serverside
  links:
    enable: true
    exclude:
      - hsinghhira.me
  sitemap:
    yoast: true
    gnews: true
  search:
    type: ["page", "post"]
  feed:
    type: [page, post]
    icon: "https://w7.pngwing.com/pngs/745/306/png-transparent-gallery-image-images-photo-picture-pictures-set-app-incredibles-icon-thumbnail.png"

generator_amp:
  templateDir: amp-template
  assetDistDir: amp-dist

hexo_safego:
  # 基本功能设置
  general:
    enable: true # 启用插件
    enable_base64_encode: true # 使用 Base64 编码
    enable_target_blank: true # 打开新窗口
    auto_redirect: false # 自动重定向
  # 安全设置
  security:
    url_param_name: "u" # URL 参数名
    html_file_name: "go.html" # 重定向页面的文件名
    ignore_attrs: # 忽略处理的 HTML 属性
      - "data-fancybox"
  # 容器与页面设置
  scope:
    apply_containers: # 应用的容器选择器
      - ".md-text"
    apply_pages: # 应用的页面路径
      - "/2025/"
    exclude_pages: # 排除的页面路径
  # 域名白名单
  whitelist:
    domain_whitelist: # 允许的白名单域名
      - "hzchu.top"
      - "creativecommons.org"
  # 页面外观设置
  appearance:
    avatar: /favicon.ico # 头像路径
    title: "Thun888" # 页面标题
    subtitle: "安全中心" # 页面副标题
    darkmode: true # 是否启用深色模式
    countdowntime: 10 # 倒计时秒数
    theme_color: "#6bb418" # 主题色
  # 调试设置
  debug:
    enable: false # 启用调试模式
  siteinfo:
    enable: true
    api: https://siteinfo-api.hzchu.top/api/v1?url={href}

robots:
  user_agent: "*"
  allow:
    - /
    - /archives/
    - /page/
    - /tags/
  disallow:
    - /js/
    - /css/
    - /images/
  sitemaps:
    - https://me.hsinghhira.me/sitemap.xml
    - https://me.hsinghhira.me/atom.xml
    - https://me.hsinghhira.me/rss.xml
    - https://me.hsinghhira.me/feed.json

cdn:
  server: https://images.weserv.nl
  use_webp: true
  native: false # use cloudflare native image resize
  max_width:
  exclude_domains:

analytics:
  google_analytics:
    enable: true
    measurement_id: G-GJF7D1TVGG
  microsoft_clarity:
    enable: true
    project_id: skvnh9ncl9
