# Site
title: Harman Singh Hira
subtitle: "Just another coder I guess..."
description: ""
keywords:
author: Harman Singh Hira
language: en
timezone: ""
url: http://me.hsinghhira.me/
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Sitemap
sitemap:
  path: /sitemap.xml
  rel: false
  tags: true
  categories: true

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: ""
  wrap: false
  hljs: false
prism_plugin:
  mode: "preprocess" # Or 'raw'
  theme: "tomorrow" # You can change to: default, okaidia, twilight, etc.
  line_number: false
  copy_button: true
  tab_replace: ""

index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

meta_generator: true

date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: "mtime"

per_page: 10
pagination_dir: page

include:
exclude:
ignore:

all_minifier: true
html_minifier: true
css_minifier: true
js_minifier: true

theme: minima

deploy:
  type: git
  repo: https://github.com/HSinghHira/Its-Me.git
  branch: page
  message: "Last Update: {{ now('MM-DD HH:mm:ss') }}"
  cname: me.hsinghhira.me

feed:
  limit: 20
  order_by: "-date"
  tag_dir: "tag"
  category_dir: "category"
  rss:
    enable: true
    template: "themes/theme/layout/_alternate/rss.ejs"
    output: "rss.xml"
  atom:
    enable: true
    template: "themes/theme/layout/_alternate/atom.ejs"
    output: "atom.xml"
  jsonFeed:
    enable: true
    template: "themes/theme/layout/_alternate/json.ejs"
    output: "feed.json"
