# Site
title: Harman Singh Hira
subtitle: "Just another coder I guess..."
description: "Welcome to my personal blog where I share my thoughts on coding, technology, and life."
keywords: Harman Singh Hira, hsinghhira, hsinghhira.me, blog, personal blog, hexo, hexo theme minima
author: Harman Singh Hira
language: en
timezone: Pacific/Auckland
url: http://me.hsinghhira.me/
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

highlight:
  enable: false
prismjs:
  enable: false
syntax_highlighter:

shiki:
  enable: true
  theme: "github-light"
  light: "github-light"
  dark: "github-dark"
  customThemesPath: ""
  supportedLangs:
    - js
    - python
    - html
    - css
    - java
    - php
    - powershell
    - bash
    - csharp
    - cpp
    - css
    - go
    - javascript
    - json
    - lua
    - markdown
    - python
    - ruby
    - rust
    - typescript
    - yaml
    - scss
    - sql
  copyButton: true
  lineNumbers: false

index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

meta_generator: true

date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: "mtime"

per_page: 10
pagination_dir: page

include:
exclude:
ignore:

all_minifier: true
html_minifier: true
css_minifier: true
js_minifier: true

theme: minima

deploy:
  type: git
  repo: https://github.com/HSinghHira/HSinghHira
  branch: gh-pages
  message: "Last Update: {{ now('MM-DD HH:mm:ss') }}"
  cname: me.hsinghhira.me

lazyload:
  enable: true
  onlypost: false
  loadingImg: # /images/loading.gif
  isSPA: false
  preloadRatio: 3

feed:
  limit: 20
  order_by: "-date"
  tag_dir: "tag"
  category_dir: "category"
  rss:
    enable: true
    output: "rss.xml"
  atom:
    enable: true
    output: "atom.xml"
  jsonFeed:
    enable: true
    output: "feed.json"

seo:
  cache: true
  html:
    enable: true
    fix: true
    exclude:
      - "*.min.{htm,html}"
    removeComments: true
    removeEmptyAttributes: true
    removeScriptTypeAttributes: true
    removeStyleLinkTypeAttributes: true
    minifyJS: true
    minifyCSS: true
  css:
    enable: true
    exclude:
      - "**/*.min.css"
      - "*.min.css"
  js:
    enable: true
    concat: false
    exclude:
      - "**/*.min.js"
    options:
      compress:
        dead_code: true
      mangle:
        toplevel: true
        safari10: true
  schema:
    article:
      enable: true
    breadcrumb:
      enable: true
    sitelink:
      enable: true
    homepage:
      enable: true
  img:
    enable: true
    broken: false
    default: https://upload.wikimedia.org/wikipedia/commons/6/65/No-Image-Placeholder.svg
    onerror: serverside
  links:
    enable: true
    blank: true
    allow:
      - hsinghhira.me
    exclude:
      - hsinghhira.me
  sitemap:
    yoast: true
    gnews: true
    txt: true
  search:
    type: ["page", "post"]
  feed:
    type: [page, post]
    icon: "https://w7.pngwing.com/pngs/745/306/png-transparent-gallery-image-images-photo-picture-pictures-set-app-incredibles-icon-thumbnail.png"

generator_amp:
  templateDir: amp-template
  assetDistDir: amp-dist

robots:
  user_agent: "*"
  allow:
    - /
    - /archives/
    - /page/
    - /tags/
  disallow:
    - /js/
    - /css/
    - /images/
  sitemaps:
    - https://me.hsinghhira.me/sitemap.xml
    - https://me.hsinghhira.me/atom.xml
    - https://me.hsinghhira.me/rss.xml
    - https://me.hsinghhira.me/feed.json

cdn:
  cdn_server: //wsrv.nl
  native: false
  cdn_use_webp: true
  max_width: [1200, 800, 400]
  exclude_domains: ["example.com", "cdn.example.org"]
  height: 600
  device_pixel_ratio: 2
  fit: "cover"
  alignment: "center"
  focal_point_x: 0.5
  focal_point_y: 0.3
  crop: [100, 100, 200, 200]
  precrop: [50, 50, 150, 150]
  trim: true
  mask: "circle"
  mask_trim: 10
  mask_background: "ffffff"
  quality: 85
  compression: 6
  lossless: false
  background: "000000"
  rotation_background: "transparent"
  blur: 5
  sharpen: 3
  sharpen_flat: 2
  sharpen_jagged: 1
  contrast: 1.2
  brightness: 0.8
  gamma: 1.5
  saturation: 1.1
  hue: 180
  modulate: [1.2, 1.3, 1.4]
  tint: "ff0000"
  filter: "greyscale"
  filter_start: "00ff00"
  filter_stop: "0000ff"
  rotation: 90
  flip: true
  flop: false
  output_format: "webp"
  encoding: "base64"
  without_enlargement: true
  adaptive_filter: true
  interlace: true
  max_age: 31536000
  page: 1
  n: -1
  filename: "test-image"
  default_image: "https://example.com/default.jpg"

analytics:
  google_analytics:
    enable: true
    measurement_id: G-GJF7D1TVGG
  microsoft_clarity:
    enable: true
    project_id: skvnh9ncl9

TagsEmbed:
  enable: true
  priority: 5
  CDN:
    tags_embed: https://cdn.jsdelivr.net/gh/docs-site/hexo-tags-embed@latest/lib/tag_embed.css
