export const SITE = {
  website: "https://me.hsinghhira.me",
  author: "Harman Singh Hira",
  profile: "https://me.hsinghhira.me",
  desc: "Welcome to my personal blog where I share my thoughts on coding, technology, and life.",
  title: "Harman Singh Hira",
  ogImage: "og.webp",
  lightAndDarkMode: true,
  postPerIndex: 8,
  postPerPage: 8,
  portfolioPerIndex: 4,
  portfolioPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: false,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Pacific/Auckland",
  googleTagManagerId: "G-289451495",
} as const;